sudo: false
language: c
 
addons:
  apt:
    packages:
    - pandoc
 
script: curl -g -s [url]https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh[/url] | bash
 
branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/