sudo: required
language: c

addons:
  apt:
    packages:
    - pandoc

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

branches:
  only:
    - shadowlands
  tags:
    - '**-alpha'

env:
  - CF_API_KEY=""
  - WOWI_API_TOKEN=""