sudo: required
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^v?9\.\d+(\.\d+)?(-\S*)?-sl$/

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
env:
  CF_API_KEY:
  WOWI_API_TOKEN:
