name: Report a Bug
description: Use this template to submit a bug report.  Incomplete reports may be rejected or closed.
title: "[Bug] "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: **Before You Begin** |
        1. Please update to the latest version of the addon, even if it is an alpha or beta version, before submitting a report.  This helps you to avoid reporting an issue that is already resolved. |
        2. Check for an existing, open ticket that matches your issue.  If there is an open ticket, simply add your snapshot and other report information to the open ticket instead.
  - type: checkboxes
    id: precheck
    attributes:
      label: **Before You Begin**
      description: Please confirm that you've taken these preliminary steps before submitting your issue report.
      options:
        - label: I confirm that I have downloaded the latest version of the addon.
          required: true
        - label: I checked for an existing, open ticket for this issue and was not able to find one.
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
