name: Report a Bug
description: Report a bug if/when the addon is not behaving the way it is expected to behave.
title: "[Bug] REPLACE THIS TEXT WITH A SHORT DESCRIPTION OF THE BUG YOU ARE REPORTING"
labels: [bug, triage]
assignees:
  - Hekili
body:
  - type: checkboxes
    id: precheck
    attributes:
      label: Before You Begin
      description: Please confirm that you've taken these preliminary steps before submitting your issue report.
      options:
        - label: I confirm that I have downloaded the latest version of the addon.
          required: true
        - label: I checked for an existing, open ticket for this issue and was not able to find one.
          required: true
        - label: I edited the title of this bug report (above) so that it describes the issue I am reporting.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Please describe the issue in question.  Be specific and describe what you see.  You can CTRL+V to paste a screenshot (image) or supply links to screenshot images.
      placeholder: "Example: The addon is not loading for my Beast Mastery Demon Hunter.  The following error message appears in my BugSack."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to Reproduce
      description: "Steps to reproduce the behavior"
      placeholder: "Example: Enter game as a Havoc Demon Hunter.  Change specialization to Beast Mastery.  Realize Beast Mastery Demon Hunters don't exist."
    validations:
      required: true
  - type: input
    id: messages
    attributes:
      label: Snapshot
      description: If you are reporting an issue with the addon's recommendations, there is a "Snapshot" feature that you will need to use.  By default, pressing `ALT-SHIFT-P` to Pause (or `ALT-SHIFT-[` to Snapshot without pausing) will generate a Snapshot, which is found in /hekili > Snapshots.  This should be done when you are seeing the recommendation you disagree with.  Copy the Snapshot to Pastebin and provide the link here.|If your issue is not related to the addon's recommendations, you can instead copy the information from /hekili > Issue Reporting to Pastebin and link that here instead.
      required: true
