name: Report a Bug
description: Report a bug if/when the addon is not behaving the way it is expected to behave.
title: "[Bug] REPLACE THIS TEXT WITH A SHORT DESCRIPTION OF THE BUG YOU ARE REPORTING"
labels: [bug, triage]
assignees:
  - Hekili
body:
  - type: 
  - type: checkboxes
    id: precheck
    attributes:
      label: Before You Begin
      description: Please confirm that you've taken these preliminary steps before submitting your issue report.
      options:
        - label: I confirm that I have downloaded the latest version of the addon.
          required: true
        - label: I checked for an existing, open ticket for this issue and was not able to find one.
          required: true
        - label: I edited the title of this bug report (above) so that it describes the issue I am reporting.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Please describe the issue in question.  Be specific and describe what you see.  You can CTRL+V to paste a screenshot (image) or supply links to screenshot images.
      placeholder: "Example: The addon is not loading for my Beast Mastery Demon Hunter.  The following error message appears in my BugSack."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to Reproduce
      description: """Steps to reproduce the behavior:
        - Go to '...'
        - Click on '....'
        - Scroll down to '....'
        - See error"""
      placeholder: Example: Enter game as a Havoc Demon Hunter.  Change specialization to Beast Mastery.  Realize Beast Mastery Demon Hunters don't exist.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
